# Site settings
title: International Formula Master 2009 by CTDP
email: info@ctdpworld.org
description: The premier addon by CTDP for Assetto Corsa brings you the 2009 season with the cars and drivers competing this season.
baseurl: "/ifm2009/" # the subpath of your site, e.g. /blog/
url: "http://readme.ctdp.net" # the base hostname & protocol for your site
twitter_username: team_ctdp
github_username:  CTDP

# Build settings
markdown: kramdown
textile_ext:  "textile"
highlighter: pygments
exclude:
  - tools
  - lib
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - config.rb
  - sass
  - drafts

# Deployment

ftp_host: 'www.ctdpworld.org'
ftp_dir: '/homepages/u28471/readme/ifm2009'
ftp_passive: false

# optional
ftp_port: 21                  # default 21
ftp_username: 'u28471'     # default read from stdin